// Autogenerated Jamon proxy
// /Users/jaywong/data/opensource/hadoop/wasp/github/wasp/src/main/jamon/./com/alibaba/wasp/tmpl/master/MasterStatusTmpl.jamon

package com.alibaba.wasp.tmpl.master;

// 32, 1
import java.util.*;
// 33, 1
import org.apache.hadoop.util.StringUtils;
// 34, 1
import org.apache.hadoop.hbase.util.Bytes;
// 35, 1
import org.apache.hadoop.hbase.util.JvmVersion;
// 36, 1
import org.apache.hadoop.hbase.util.FSUtils;
// 37, 1
import com.alibaba.wasp.master.FMaster;
// 38, 1
import com.alibaba.wasp.client.WaspAdmin;
// 39, 1
import org.apache.hadoop.hbase.HConstants;
// 40, 1
import com.alibaba.wasp.ServerName;
// 41, 1
import org.apache.hadoop.hbase.client.HBaseAdmin;
// 42, 1
import com.alibaba.wasp.client.FConnectionManager;
// 43, 1
import com.alibaba.wasp.meta.FTable;
// 44, 1
import org.apache.hadoop.hbase.HBaseConfiguration;

@org.jamon.annotations.Template(
  signature = "DA9F98A903307DE1B5CECB40D6ACDC0B",
  requiredArguments = {
    @org.jamon.annotations.Argument(name = "master", type = "FMaster"),
    @org.jamon.annotations.Argument(name = "admin", type = "WaspAdmin")},
  optionalArguments = {
    @org.jamon.annotations.Argument(name = "servers", type = "List<ServerName>"),
    @org.jamon.annotations.Argument(name = "frags", type = "Map<String,Integer>"),
    @org.jamon.annotations.Argument(name = "deadServers", type = "Set<ServerName>"),
    @org.jamon.annotations.Argument(name = "showAppendWarning", type = "boolean"),
    @org.jamon.annotations.Argument(name = "filter", type = "String"),
    @org.jamon.annotations.Argument(name = "format", type = "String"),
    @org.jamon.annotations.Argument(name = "catalogJanitorEnabled", type = "boolean")})
public class MasterStatusTmpl
  extends org.jamon.AbstractTemplateProxy
{
  
  public MasterStatusTmpl(org.jamon.TemplateManager p_manager)
  {
     super(p_manager);
  }
  
  public MasterStatusTmpl()
  {
     super("/com/alibaba/wasp/tmpl/master/MasterStatusTmpl");
  }
  
  protected interface Intf
    extends org.jamon.AbstractTemplateProxy.Intf{
    
    void renderNoFlush(final java.io.Writer jamonWriter) throws java.io.IOException;
    
  }
  public static class ImplData
    extends org.jamon.AbstractTemplateProxy.ImplData
  {
    // 20, 1
    public void setMaster(FMaster master)
    {
      // 20, 1
      m_master = master;
    }
    public FMaster getMaster()
    {
      return m_master;
    }
    private FMaster m_master;
    // 21, 1
    public void setAdmin(WaspAdmin admin)
    {
      // 21, 1
      m_admin = admin;
    }
    public WaspAdmin getAdmin()
    {
      return m_admin;
    }
    private WaspAdmin m_admin;
    // 24, 1
    public void setServers(List<ServerName> servers)
    {
      // 24, 1
      m_servers = servers;
      m_servers__IsNotDefault = true;
    }
    public List<ServerName> getServers()
    {
      return m_servers;
    }
    private List<ServerName> m_servers;
    public boolean getServers__IsNotDefault()
    {
      return m_servers__IsNotDefault;
    }
    private boolean m_servers__IsNotDefault;
    // 22, 1
    public void setFrags(Map<String,Integer> frags)
    {
      // 22, 1
      m_frags = frags;
      m_frags__IsNotDefault = true;
    }
    public Map<String,Integer> getFrags()
    {
      return m_frags;
    }
    private Map<String,Integer> m_frags;
    public boolean getFrags__IsNotDefault()
    {
      return m_frags__IsNotDefault;
    }
    private boolean m_frags__IsNotDefault;
    // 25, 1
    public void setDeadServers(Set<ServerName> deadServers)
    {
      // 25, 1
      m_deadServers = deadServers;
      m_deadServers__IsNotDefault = true;
    }
    public Set<ServerName> getDeadServers()
    {
      return m_deadServers;
    }
    private Set<ServerName> m_deadServers;
    public boolean getDeadServers__IsNotDefault()
    {
      return m_deadServers__IsNotDefault;
    }
    private boolean m_deadServers__IsNotDefault;
    // 26, 1
    public void setShowAppendWarning(boolean showAppendWarning)
    {
      // 26, 1
      m_showAppendWarning = showAppendWarning;
      m_showAppendWarning__IsNotDefault = true;
    }
    public boolean getShowAppendWarning()
    {
      return m_showAppendWarning;
    }
    private boolean m_showAppendWarning;
    public boolean getShowAppendWarning__IsNotDefault()
    {
      return m_showAppendWarning__IsNotDefault;
    }
    private boolean m_showAppendWarning__IsNotDefault;
    // 28, 1
    public void setFilter(String filter)
    {
      // 28, 1
      m_filter = filter;
      m_filter__IsNotDefault = true;
    }
    public String getFilter()
    {
      return m_filter;
    }
    private String m_filter;
    public boolean getFilter__IsNotDefault()
    {
      return m_filter__IsNotDefault;
    }
    private boolean m_filter__IsNotDefault;
    // 29, 1
    public void setFormat(String format)
    {
      // 29, 1
      m_format = format;
      m_format__IsNotDefault = true;
    }
    public String getFormat()
    {
      return m_format;
    }
    private String m_format;
    public boolean getFormat__IsNotDefault()
    {
      return m_format__IsNotDefault;
    }
    private boolean m_format__IsNotDefault;
    // 27, 1
    public void setCatalogJanitorEnabled(boolean catalogJanitorEnabled)
    {
      // 27, 1
      m_catalogJanitorEnabled = catalogJanitorEnabled;
      m_catalogJanitorEnabled__IsNotDefault = true;
    }
    public boolean getCatalogJanitorEnabled()
    {
      return m_catalogJanitorEnabled;
    }
    private boolean m_catalogJanitorEnabled;
    public boolean getCatalogJanitorEnabled__IsNotDefault()
    {
      return m_catalogJanitorEnabled__IsNotDefault;
    }
    private boolean m_catalogJanitorEnabled__IsNotDefault;
  }
  @Override
  protected ImplData makeImplData()
  {
    return new ImplData();
  }
  @Override @SuppressWarnings("unchecked") public ImplData getImplData()
  {
    return (ImplData) super.getImplData();
  }
  
  protected List<ServerName> servers;
  public final com.alibaba.wasp.tmpl.master.MasterStatusTmpl setServers(List<ServerName> p_servers)
  {
    (getImplData()).setServers(p_servers);
    return this;
  }
  
  protected Map<String,Integer> frags;
  public final com.alibaba.wasp.tmpl.master.MasterStatusTmpl setFrags(Map<String,Integer> p_frags)
  {
    (getImplData()).setFrags(p_frags);
    return this;
  }
  
  protected Set<ServerName> deadServers;
  public final com.alibaba.wasp.tmpl.master.MasterStatusTmpl setDeadServers(Set<ServerName> p_deadServers)
  {
    (getImplData()).setDeadServers(p_deadServers);
    return this;
  }
  
  protected boolean showAppendWarning;
  public final com.alibaba.wasp.tmpl.master.MasterStatusTmpl setShowAppendWarning(boolean p_showAppendWarning)
  {
    (getImplData()).setShowAppendWarning(p_showAppendWarning);
    return this;
  }
  
  protected String filter;
  public final com.alibaba.wasp.tmpl.master.MasterStatusTmpl setFilter(String p_filter)
  {
    (getImplData()).setFilter(p_filter);
    return this;
  }
  
  protected String format;
  public final com.alibaba.wasp.tmpl.master.MasterStatusTmpl setFormat(String p_format)
  {
    (getImplData()).setFormat(p_format);
    return this;
  }
  
  protected boolean catalogJanitorEnabled;
  public final com.alibaba.wasp.tmpl.master.MasterStatusTmpl setCatalogJanitorEnabled(boolean p_catalogJanitorEnabled)
  {
    (getImplData()).setCatalogJanitorEnabled(p_catalogJanitorEnabled);
    return this;
  }
  
  
  @Override
  public org.jamon.AbstractTemplateImpl constructImpl(Class<? extends org.jamon.AbstractTemplateImpl> p_class){
    try
    {
      return p_class
        .getConstructor(new Class [] { org.jamon.TemplateManager.class, ImplData.class })
        .newInstance(new Object [] { getTemplateManager(), getImplData()});
    }
    catch (RuntimeException e)
    {
      throw e;
    }
    catch (Exception e)
    {
      throw new RuntimeException(e);
    }
  }
  
  @Override
  protected org.jamon.AbstractTemplateImpl constructImpl(){
    return new MasterStatusTmplImpl(getTemplateManager(), getImplData());
  }
  public org.jamon.Renderer makeRenderer(final FMaster master, final WaspAdmin admin)
  {
    return new org.jamon.AbstractRenderer() {
      @Override
      public void renderTo(final java.io.Writer jamonWriter)
        throws java.io.IOException
      {
        render(jamonWriter, master, admin);
      }
    };
  }
  
  public void render(final java.io.Writer jamonWriter, final FMaster master, final WaspAdmin admin)
    throws java.io.IOException
  {
    renderNoFlush(jamonWriter, master, admin);
    jamonWriter.flush();
  }
  public void renderNoFlush(final java.io.Writer jamonWriter, final FMaster master, final WaspAdmin admin)
    throws java.io.IOException
  {
    ImplData implData = getImplData();
    implData.setMaster(master);
    implData.setAdmin(admin);
    Intf instance = (Intf) getTemplateManager().constructImpl(this);
    instance.renderNoFlush(jamonWriter);
    reset();
  }
  
  
}
