// Autogenerated Jamon proxy
// /Users/jaywong/data/opensource/hadoop/wasp/trunk/src/main/jamon/./org/apache/wasp/tmpl/master/FServerListTmpl.jamon

package org.apache.wasp.tmpl.master;

// 27, 9
import java.util.*;
// 28, 9
import org.apache.hadoop.util.StringUtils;
// 29, 9
import org.apache.hadoop.hbase.util.Bytes;
// 30, 9
import org.apache.hadoop.hbase.util.JvmVersion;
// 31, 9
import org.apache.hadoop.hbase.util.FSUtils;
// 32, 9
import org.apache.wasp.master.FMaster;
// 33, 9
import org.apache.hadoop.hbase.HConstants;
// 34, 9
import org.apache.wasp.ServerLoad;
// 35, 9
import org.apache.wasp.ServerName;
// 36, 9
import org.apache.hadoop.hbase.client.HBaseAdmin;
// 37, 9
import org.apache.hadoop.hbase.client.HConnectionManager;
// 38, 9
import org.apache.hadoop.hbase.HTableDescriptor;
// 39, 9
import org.apache.hadoop.hbase.HBaseConfiguration;

@org.jamon.annotations.Template(
  signature = "54E9F4AF828FDBABAC32A909F0C31865",
  requiredArguments = {
    @org.jamon.annotations.Argument(name = "master", type = "FMaster")},
  optionalArguments = {
    @org.jamon.annotations.Argument(name = "servers", type = "List<ServerName>")})
public class FServerListTmpl
  extends org.jamon.AbstractTemplateProxy
{
  
  public FServerListTmpl(org.jamon.TemplateManager p_manager)
  {
     super(p_manager);
  }
  
  public FServerListTmpl()
  {
     super("/org/apache/wasp/tmpl/master/FServerListTmpl");
  }
  
  protected interface Intf
    extends org.jamon.AbstractTemplateProxy.Intf{
    
    void renderNoFlush(final java.io.Writer jamonWriter) throws java.io.IOException;
    
  }
  public static class ImplData
    extends org.jamon.AbstractTemplateProxy.ImplData
  {
    // 23, 1
    public void setMaster(FMaster master)
    {
      // 23, 1
      m_master = master;
    }
    public FMaster getMaster()
    {
      return m_master;
    }
    private FMaster m_master;
    // 22, 1
    public void setServers(List<ServerName> servers)
    {
      // 22, 1
      m_servers = servers;
      m_servers__IsNotDefault = true;
    }
    public List<ServerName> getServers()
    {
      return m_servers;
    }
    private List<ServerName> m_servers;
    public boolean getServers__IsNotDefault()
    {
      return m_servers__IsNotDefault;
    }
    private boolean m_servers__IsNotDefault;
  }
  @Override
  protected ImplData makeImplData()
  {
    return new ImplData();
  }
  @Override @SuppressWarnings("unchecked") public ImplData getImplData()
  {
    return (ImplData) super.getImplData();
  }
  
  protected List<ServerName> servers;
  public final org.apache.wasp.tmpl.master.FServerListTmpl setServers(List<ServerName> p_servers)
  {
    (getImplData()).setServers(p_servers);
    return this;
  }
  
  
  @Override
  public org.jamon.AbstractTemplateImpl constructImpl(Class<? extends org.jamon.AbstractTemplateImpl> p_class){
    try
    {
      return p_class
        .getConstructor(new Class [] { org.jamon.TemplateManager.class, ImplData.class })
        .newInstance(new Object [] { getTemplateManager(), getImplData()});
    }
    catch (RuntimeException e)
    {
      throw e;
    }
    catch (Exception e)
    {
      throw new RuntimeException(e);
    }
  }
  
  @Override
  protected org.jamon.AbstractTemplateImpl constructImpl(){
    return new FServerListTmplImpl(getTemplateManager(), getImplData());
  }
  public org.jamon.Renderer makeRenderer(final FMaster master)
  {
    return new org.jamon.AbstractRenderer() {
      @Override
      public void renderTo(final java.io.Writer jamonWriter)
        throws java.io.IOException
      {
        render(jamonWriter, master);
      }
    };
  }
  
  public void render(final java.io.Writer jamonWriter, final FMaster master)
    throws java.io.IOException
  {
    renderNoFlush(jamonWriter, master);
    jamonWriter.flush();
  }
  public void renderNoFlush(final java.io.Writer jamonWriter, final FMaster master)
    throws java.io.IOException
  {
    ImplData implData = getImplData();
    implData.setMaster(master);
    Intf instance = (Intf) getTemplateManager().constructImpl(this);
    instance.renderNoFlush(jamonWriter);
    reset();
  }
  
  
}
