// Autogenerated Jamon implementation
// /Users/jaywong/data/opensource/hadoop/wasp/github/wasp/src/main/jamon/./com/alibaba/wasp/tmpl/fserver/EntityGroupListTmpl.jamon

package com.alibaba.wasp.tmpl.fserver;

// 24, 9
import java.util.*;
// 25, 9
import com.alibaba.wasp.fserver.FServer;
// 26, 9
import org.apache.hadoop.hbase.util.Bytes;
// 27, 9
import com.alibaba.wasp.EntityGroupInfo;
// 28, 9
import org.apache.hadoop.hbase.ServerName;
// 29, 9
import org.apache.hadoop.hbase.HBaseConfiguration;
// 30, 9
import com.alibaba.wasp.EntityGroupLoad;

public class EntityGroupListTmplImpl
  extends org.jamon.AbstractTemplateImpl
  implements com.alibaba.wasp.tmpl.fserver.EntityGroupListTmpl.Intf

{
  private final FServer fserver;
  private final List<EntityGroupInfo> onlineEntityGroups;
  protected static com.alibaba.wasp.tmpl.fserver.EntityGroupListTmpl.ImplData __jamon_setOptionalArguments(com.alibaba.wasp.tmpl.fserver.EntityGroupListTmpl.ImplData p_implData)
  {
    return p_implData;
  }
  public EntityGroupListTmplImpl(org.jamon.TemplateManager p_templateManager, com.alibaba.wasp.tmpl.fserver.EntityGroupListTmpl.ImplData p_implData)
  {
    super(p_templateManager, __jamon_setOptionalArguments(p_implData));
    fserver = p_implData.getFserver();
    onlineEntityGroups = p_implData.getOnlineEntityGroups();
  }
  
  public void renderNoFlush(@SuppressWarnings({"unused","hiding"}) final java.io.Writer jamonWriter)
    throws java.io.IOException
  {
    // 32, 1
    if ((onlineEntityGroups != null && onlineEntityGroups.size() > 0) )
    {
      // 32, 70
      jamonWriter.write("\n\n    ");
      // 34, 5
      
        Collections.sort(onlineEntityGroups);
    
      // 38, 5
      jamonWriter.write("<div class=\"tabbable\">\n        <ul class=\"nav nav-pills\">\n            <li class=\"active\"><a href=\"#tab_regionBaseInfo\" data-toggle=\"tab\">Base Info</a> </li>\n            <li><a href=\"#tab_entityGroupRequestStats\" data-toggle=\"tab\">Request metrics</a></li>\n        </ul>\n        <div class=\"tab-content\" style=\"padding-bottom: 9px; border-bottom: 1px solid #ddd;\">\n            <div class=\"tab-pane active\" id=\"tab_regionBaseInfo\">\n                ");
      // 45, 17
      {
        // 45, 17
        __jamon_innerUnit__baseInfo(jamonWriter, onlineEntityGroups);
      }
      // 45, 73
      jamonWriter.write("\n            </div>\n            <div class=\"tab-pane\" id=\"tab_entityGroupRequestStats\">\n                ");
      // 48, 17
      {
        // 48, 17
        __jamon_innerUnit__requestStats(jamonWriter, onlineEntityGroups);
      }
      // 48, 77
      jamonWriter.write("\n            </div>\n        </div>\n    </div>\n");
    }
    // 52, 1
    else
    {
      // 52, 8
      jamonWriter.write("\n    <p>Not serving entityGroups</p>\n");
    }
    // 54, 7
    jamonWriter.write("\n\n");
  }
  
  
  // 77, 1
  private void __jamon_innerUnit__requestStats(@SuppressWarnings({"unused","hiding"}) final java.io.Writer jamonWriter, final List<EntityGroupInfo> onlineEntityGroups)
    throws java.io.IOException
  {
    // 81, 5
    jamonWriter.write("<table class=\"table table-striped\">\n        <tr>\n            <th>EntityGroup Name</th>\n            <th>Read Request Count</th>\n            <th>Write Request Count</th>\n        </tr>\n\n        ");
    // 88, 9
    for (EntityGroupInfo egi: onlineEntityGroups )
    {
      // 88, 57
      jamonWriter.write("\n\n        <tr>\n        ");
      // 91, 9
      
            EntityGroupLoad load = fserver.createEntityGroupLoad(egi);
        
      // 94, 13
      jamonWriter.write("<td>");
      // 94, 17
      org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(egi.getEntityGroupNameAsString()), jamonWriter);
      // 94, 55
      jamonWriter.write("</td>\n            ");
      // 95, 13
      if (load != null )
      {
        // 95, 33
        jamonWriter.write("\n            <td>");
        // 96, 17
        org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(load.getReadRequestsCount()), jamonWriter);
        // 96, 50
        jamonWriter.write("</td>\n            <td>");
        // 97, 17
        org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(load.getWriteRequestsCount()), jamonWriter);
        // 97, 51
        jamonWriter.write("</td>\n            ");
      }
      // 98, 19
      jamonWriter.write("\n        </tr>\n        ");
    }
    // 100, 16
    jamonWriter.write("\n    </table>\n");
  }
  
  
  // 113, 1
  private void __jamon_innerUnit__compactStats(@SuppressWarnings({"unused","hiding"}) final java.io.Writer jamonWriter, final List<EntityGroupInfo> onlineEntityGroups)
  {
  }
  
  
  // 56, 1
  private void __jamon_innerUnit__baseInfo(@SuppressWarnings({"unused","hiding"}) final java.io.Writer jamonWriter, final List<EntityGroupInfo> onlineEntityGroups)
    throws java.io.IOException
  {
    // 60, 5
    jamonWriter.write("<table class=\"table table-striped\">\n        <tr>\n            <th>EntityGroup Name</th>\n            <th>Start Key</th>\n            <th>End Key</th>\n        </tr>\n\n        ");
    // 67, 9
    for (EntityGroupInfo egi: onlineEntityGroups )
    {
      // 67, 57
      jamonWriter.write("\n        <tr>\n            <td>");
      // 69, 17
      org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(egi.getEntityGroupNameAsString()), jamonWriter);
      // 69, 55
      jamonWriter.write("</td>\n            <td>");
      // 70, 17
      org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(Bytes.toStringBinary(egi.getStartKey())), jamonWriter);
      // 70, 62
      jamonWriter.write("</td>\n            <td>");
      // 71, 17
      org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(Bytes.toStringBinary(egi.getEndKey())), jamonWriter);
      // 71, 60
      jamonWriter.write("</td>\n        </tr>\n        ");
    }
    // 73, 16
    jamonWriter.write("\n    </table>\n");
  }
  
  
  // 105, 1
  private void __jamon_innerUnit__storeStats(@SuppressWarnings({"unused","hiding"}) final java.io.Writer jamonWriter, final List<EntityGroupInfo> onlineEntityGroups)
  {
  }
  
  
}
