// Autogenerated Jamon proxy
// /Users/jaywong/data/opensource/hadoop/wasp/github/wasp/src/main/jamon/./com/alibaba/wasp/tmpl/fserver/EntityGroupListTmpl.jamon

package com.alibaba.wasp.tmpl.fserver;

// 24, 9
import java.util.*;
// 25, 9
import com.alibaba.wasp.fserver.FServer;
// 26, 9
import org.apache.hadoop.hbase.util.Bytes;
// 27, 9
import com.alibaba.wasp.EntityGroupInfo;
// 28, 9
import org.apache.hadoop.hbase.ServerName;
// 29, 9
import org.apache.hadoop.hbase.HBaseConfiguration;
// 30, 9
import com.alibaba.wasp.EntityGroupLoad;

@org.jamon.annotations.Template(
  signature = "07FF2B5346AC169FE311A609449FAD39",
  requiredArguments = {
    @org.jamon.annotations.Argument(name = "fserver", type = "FServer"),
    @org.jamon.annotations.Argument(name = "onlineEntityGroups", type = "List<EntityGroupInfo>")})
public class EntityGroupListTmpl
  extends org.jamon.AbstractTemplateProxy
{
  
  public EntityGroupListTmpl(org.jamon.TemplateManager p_manager)
  {
     super(p_manager);
  }
  
  public EntityGroupListTmpl()
  {
     super("/com/alibaba/wasp/tmpl/fserver/EntityGroupListTmpl");
  }
  
  protected interface Intf
    extends org.jamon.AbstractTemplateProxy.Intf{
    
    void renderNoFlush(final java.io.Writer jamonWriter) throws java.io.IOException;
    
  }
  public static class ImplData
    extends org.jamon.AbstractTemplateProxy.ImplData
  {
    // 20, 9
    public void setFserver(FServer fserver)
    {
      // 20, 9
      m_fserver = fserver;
    }
    public FServer getFserver()
    {
      return m_fserver;
    }
    private FServer m_fserver;
    // 21, 9
    public void setOnlineEntityGroups(List<EntityGroupInfo> onlineEntityGroups)
    {
      // 21, 9
      m_onlineEntityGroups = onlineEntityGroups;
    }
    public List<EntityGroupInfo> getOnlineEntityGroups()
    {
      return m_onlineEntityGroups;
    }
    private List<EntityGroupInfo> m_onlineEntityGroups;
  }
  @Override
  protected ImplData makeImplData()
  {
    return new ImplData();
  }
  @Override @SuppressWarnings("unchecked") public ImplData getImplData()
  {
    return (ImplData) super.getImplData();
  }
  
  
  @Override
  public org.jamon.AbstractTemplateImpl constructImpl(Class<? extends org.jamon.AbstractTemplateImpl> p_class){
    try
    {
      return p_class
        .getConstructor(new Class [] { org.jamon.TemplateManager.class, ImplData.class })
        .newInstance(new Object [] { getTemplateManager(), getImplData()});
    }
    catch (RuntimeException e)
    {
      throw e;
    }
    catch (Exception e)
    {
      throw new RuntimeException(e);
    }
  }
  
  @Override
  protected org.jamon.AbstractTemplateImpl constructImpl(){
    return new EntityGroupListTmplImpl(getTemplateManager(), getImplData());
  }
  public org.jamon.Renderer makeRenderer(final FServer fserver, final List<EntityGroupInfo> onlineEntityGroups)
  {
    return new org.jamon.AbstractRenderer() {
      @Override
      public void renderTo(final java.io.Writer jamonWriter)
        throws java.io.IOException
      {
        render(jamonWriter, fserver, onlineEntityGroups);
      }
    };
  }
  
  public void render(final java.io.Writer jamonWriter, final FServer fserver, final List<EntityGroupInfo> onlineEntityGroups)
    throws java.io.IOException
  {
    renderNoFlush(jamonWriter, fserver, onlineEntityGroups);
    jamonWriter.flush();
  }
  public void renderNoFlush(final java.io.Writer jamonWriter, final FServer fserver, final List<EntityGroupInfo> onlineEntityGroups)
    throws java.io.IOException
  {
    ImplData implData = getImplData();
    implData.setFserver(fserver);
    implData.setOnlineEntityGroups(onlineEntityGroups);
    Intf instance = (Intf) getTemplateManager().constructImpl(this);
    instance.renderNoFlush(jamonWriter);
    reset();
  }
  
  
}
