// Autogenerated Jamon implementation
// /Users/jaywong/data/opensource/hadoop/wasp/github/wasp/src/main/jamon/./com/alibaba/wasp/tmpl/fserver/ServerMetricsTmpl.jamon

package com.alibaba.wasp.tmpl.fserver;

// 23, 1
import java.util.*;
// 24, 1
import org.apache.hadoop.hbase.regionserver.HRegionServer;
// 25, 1
import com.alibaba.wasp.fserver.metrics.MetricsFServerWrapper;
// 26, 1
import org.apache.hadoop.hbase.util.Bytes;
// 27, 1
import org.apache.hadoop.hbase.HRegionInfo;
// 28, 1
import org.apache.hadoop.hbase.ServerName;
// 29, 1
import org.apache.hadoop.hbase.HBaseConfiguration;
// 30, 1
import org.apache.hadoop.hbase.metrics.histogram.MetricsHistogram;
// 31, 1
import com.yammer.metrics.stats.Snapshot;
// 32, 1
import java.lang.management.ManagementFactory;

public class ServerMetricsTmplImpl
  extends org.jamon.AbstractTemplateImpl
  implements com.alibaba.wasp.tmpl.fserver.ServerMetricsTmpl.Intf

{
  private final MetricsFServerWrapper mWrap;
  protected static com.alibaba.wasp.tmpl.fserver.ServerMetricsTmpl.ImplData __jamon_setOptionalArguments(com.alibaba.wasp.tmpl.fserver.ServerMetricsTmpl.ImplData p_implData)
  {
    return p_implData;
  }
  public ServerMetricsTmplImpl(org.jamon.TemplateManager p_templateManager, com.alibaba.wasp.tmpl.fserver.ServerMetricsTmpl.ImplData p_implData)
  {
    super(p_templateManager, __jamon_setOptionalArguments(p_implData));
    mWrap = p_implData.getMWrap();
  }
  
  public void renderNoFlush(@SuppressWarnings({"unused","hiding"}) final java.io.Writer jamonWriter)
    throws java.io.IOException
  {
    // 34, 1
    jamonWriter.write("<div class=\"tabbable\">\n    <ul class=\"nav nav-pills\">\n        <li class=\"active\"><a href=\"#tab_baseStats\" data-toggle=\"tab\">Base Stats</a></li>\n        <li class=\"\"><a href=\"#tab_requestStats\" data-toggle=\"tab\">Requests</a></li>\n    </ul>\n    <div class=\"tab-content\" style=\"padding-bottom: 9px; border-bottom: 1px solid #ddd;\">\n        <div class=\"tab-pane active\" id=\"tab_baseStats\">\n            ");
    // 41, 13
    {
      // 41, 13
      __jamon_innerUnit__baseStats(jamonWriter, mWrap );
    }
    // 41, 43
    jamonWriter.write("\n        </div>\n        <div class=\"tab-pane\" id=\"tab_requestStats\">\n            ");
    // 44, 13
    {
      // 44, 13
      __jamon_innerUnit__requestStats(jamonWriter, mWrap );
    }
    // 44, 46
    jamonWriter.write("\n        </div>\n    </div>\n</div>\n\n");
  }
  
  
  // 98, 1
  private void __jamon_innerUnit__requestStats(@SuppressWarnings({"unused","hiding"}) final java.io.Writer jamonWriter, final MetricsFServerWrapper mWrap)
    throws java.io.IOException
  {
    // 102, 1
    jamonWriter.write("<table class=\"table table-striped\">\n<tr>\n    <th>Request Per Second</th>\n</tr>\n<tr>\n    <td>");
    // 107, 9
    org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(mWrap.getRequestsPerSecond()), jamonWriter);
    // 107, 43
    jamonWriter.write("</td>\n</tr>\n</table>\n");
  }
  
  
  // 112, 1
  private void __jamon_innerUnit__queueStats(@SuppressWarnings({"unused","hiding"}) final java.io.Writer jamonWriter, final MetricsFServerWrapper mWrap)
  {
  }
  
  
  // 119, 1
  private void __jamon_innerUnit__blockCacheStats(@SuppressWarnings({"unused","hiding"}) final java.io.Writer jamonWriter, final MetricsFServerWrapper mWrap)
  {
  }
  
  
  // 68, 1
  private void __jamon_innerUnit__memoryStats(@SuppressWarnings({"unused","hiding"}) final java.io.Writer jamonWriter, final MetricsFServerWrapper mWrap)
    throws java.io.IOException
  {
    // 72, 1
    jamonWriter.write("<table class=\"table table-striped\">\n<tr>\n    <tr>\n        <th>Used Heap</th>\n        <th>Max Heap</th>\n    </tr>\n</tr>\n<tr>\n    <td>\n        ");
    // 81, 9
    org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(ManagementFactory.getMemoryMXBean().getHeapMemoryUsage().getUsed()), jamonWriter);
    // 81, 81
    jamonWriter.write("\n    </td>\n    <td>\n        ");
    // 84, 9
    org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(ManagementFactory.getMemoryMXBean().getHeapMemoryUsage().getMax()), jamonWriter);
    // 84, 79
    jamonWriter.write("\n    </td>\n</tr>\n</table>\n");
  }
  
  
  // 49, 1
  private void __jamon_innerUnit__baseStats(@SuppressWarnings({"unused","hiding"}) final java.io.Writer jamonWriter, final MetricsFServerWrapper mWrap)
    throws java.io.IOException
  {
    // 53, 1
    jamonWriter.write("<table class=\"table table-striped\">\n    <tr>\n\n        <th>Requests Per Second</th>\n        <th>Num. EntityGroups</th>\n        <th>Slow HLog Append Count</th>\n    </tr>\n    <tr>\n        <td>");
    // 61, 13
    org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(mWrap.getRequestsPerSecond()), jamonWriter);
    // 61, 47
    jamonWriter.write("</td>\n        <td>");
    // 62, 13
    org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(mWrap.getNumOnlineEntityGroups()), jamonWriter);
    // 62, 51
    jamonWriter.write("</td>\n        <td>");
    // 63, 13
    org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(0), jamonWriter);
    // 63, 20
    jamonWriter.write("</td>\n    </tr>\n</table>\n");
  }
  
  
  // 90, 1
  private void __jamon_innerUnit__storeStats(@SuppressWarnings({"unused","hiding"}) final java.io.Writer jamonWriter, final MetricsFServerWrapper mWrap)
  {
  }
  
  
}
